### ISSUE TITLE
Widget error

### ISSUE THREAD

**Issue by mickyunstuck** [chrislennon/Crypto-Touchbar-App#100]
Hi there,

First of all I LOVE your widget, it has finally put the touchbar to good use haha!

I set it up a few days ago and it was working nicely but yesterday it dropped out and returned an error, then was working again hours later, today the same thing however it never came back to life. Here's what it says:

```
**Traceback (most recent call last)
File "<string>", line 25, in <module>**

```

If you have the time, mind taking a look at this?

Oh! **Live update**: it just came back while I was writing this up. Would you know what causes this?

Thanks a lot man, much appreciated!

**Comment by mickyunstuck** [comment]
Oh, just saw that a comment with the same error message had been posted already, sorry about the duplicate! Were you guys able to figure out what caused it? Thanks again!

**Comment by chrislennon** [comment]
Hey @mickyunstuck thanks for reaching out, great to hear you get use from it! Sorry for the cryptic error message, I always intended to make that more visible - but haven't got around to refactoring the code in a while.

I think what is happening with your issue is I believe a rate limit by the provider of the prices. [This issue](https://github.com/chrislennon/Crypto-Touchbar-App/issues/95#issuecomment-616113850) touched on the same issue as you noticed. I believe the best course of action is to reduce the rate at which you request prices from them. 

You could probably reduce this with the frequency of the refresh, the number of coins requested. If you check out my comment in that link and see if it resolves your issue. One thing to keep in mind is that if you are currently being rate limited/blocked and you change the settings, the tool may not work immediately until rates reset. If I recall CryptoCompare run hourly and daily rate limits so these limits reset after a while.

Let me know how you get on, no issue with the duplicate issue 😄

**Comment by mickyunstuck** [comment]
Hi Chris,

Thanks for your kind reply! That did the trick, I guess I was too eager to
stay up to date on BTC values haha!
Thanks so much, that'll make me miss the touchbar on the upcoming MBP
models :D

Have a great day!
Miro

**Comment by 0xthaner** [comment]
Hey, i have the same issue - but the crux is i also cant download a new BTT because your page do not show me any currencies to choose? 😳
Maybe i do something wrong?

**Comment by chrislennon** [comment]
Hey @paranoidnakamoto which browser are you using? I seem to be able to see and select coins using Chrome on Mac. Perhaps a screenshot of what you are seeing may help.

**Comment by 0xthaner** [comment]
Hey @chrislennon thanks for your answer :) 
I use Brave - Chrome - and Safari and i can not select any CC for the direct download for BTT and the TB says: 

`**Traceback (most recent call last)
File "<string>", line 25, in <module>**
`
The browsers shows me this: 

<img width="1680" alt="Bildschirmfoto 2021-03-13 um 23 13 47" src="https://user-images.githubusercontent.com/59724145/111051331-919b7080-8452-11eb-88e3-df7abc7c4c8f.png">

Thanks for your time and reaction 
BR

**Comment by chrislennon** [comment]
thanks @paranoidnakamoto could you try going to [the cryptocompare API ](https://min-api.cryptocompare.com/data/all/coinlist)to see if you are getting any data, if you are being rate limited, i suspect you may see an error there. It could be very possible rate limiting from the touchbar could also effect the list of coins received from them.

**Comment by 0xthaner** [comment]
Hey @chrislennon, 
very strange - now suddenly it works without any api "cryptocompare" check via BTT 🤔
But thanks for your help! I bookmark this issue for the next time. ^^

Have a nice week bro! and thanks for your nice Work

**Comment by awkwardsky** [comment]
Hello @chrislennon , I have the same issue. 
`
Traceback (most recent call last)
File "<string>", line 25, in <module>
`
when I'm going to [the cryptocompare API](https://min-api.cryptocompare.com/data/all/coinlist) 
I get the response
```
{
  "Response": "Error",
  "Message": "You are over your rate limit please upgrade your account!",
  "HasWarning": false,
  "Type": 99,
  "RateLimit": {
    "calls_made": {
      "second": 1,
      "minute": 2,
      "hour": 86,
      "day": 11204,
      "month": 44957,
      "total_calls": 136537
    },
    "max_calls": {
      "second": 20,
      "minute": 300,
      "hour": 3000,
      "day": 7500,
      "month": 50000
    }
  },
  "Data": {
    
  }
}
```
thanks for you time.

**Comment by chrislennon** [comment]
Hey @awkwardsky thanks for reporting this and taking the time to check the Crypto Compare API too.

Looks like you are falling into the rate-limiting imposed by this API too, specifically the one stopping you above would be the daily calls. Their limit `7 500` where your IP (I believe this is their metric) has requested `11 204`.

My advice would be to turn down the request time on each currency pairing. This can be done within the web-app where it states 'Refresh Interval' but also with previously imported widgets you should be able to locate the same feature on each pairing.

Please note that if you have recently changed this the rate-limiting will still apply until their hour/daily/monthly metrics reset. 

If I ever get around to refactoring this code I will see if there are measures I can do to reduce the number of calls needed, however, I suspect this may be a limitation of the API as each pairing needs to make a call each refresh interval. (number of coin pairing widgets * refresh interval = lots of calls)

**Comment by awkwardsky** [comment]
> ...I suspect this may be a limitation of the API as each pairing needs to make a call each refresh interval. (number of coin pairing widgets * refresh interval = lots of calls)
 
 thx for immediately to reply.
I think you are right about calculation the “lots of call”
Because, I use your amazing app, just one day and little more.

---
my preference below:
refresh interval: 1 times/10s
number of token: 5
2 days = 17280 times
calls = (17280 times *5 token)*another one device in the same network ≒  136537

---
btw, another one device almost occurred the issue at the same time.


hope i don't need to reduce refresh frequency,
month max_calls is too few not enough to use.
everyone wanna to know the latest price at first time right ? haha

thank again

**Comment by chrislennon** [comment]
Hey @awkwardsky sorry for not getting back to you sooner. With regards to the calls not adding up to `136 537`, I suspect (but not 100% sure) that this number relates to all calls made to the API (likely from that IP address). For example, these could have been calls from other devices or calls made in previous `month` buckets.

With respect to the month's max calls, yeah their public (IP based) rate limiting is quite restrictive these days. For example assuming 1 device, 1 crypto pair, running 24/7 for a month would result in. 

`50 000 max_calls / (30 days * 24 hours * 60 minutes) = ~1 call per minute`

For routes ahead I can see the following:

1.  Reducing the refresh rate, number of coins, and number of devices that are still calling whilst not being used
2. I see that CryptoCompare has a [free tier ](https://min-api.cryptocompare.com/pricing) on their private API, this seems to increase the monthly cap from 50k to 100k

    - If you wanted to use this after obtaining an API key you would need to add it into the URL inside the script that BTT uses to call the API. In essence you would be looking for [this line](https://github.com/chrislennon/Crypto-Touchbar-App/blob/master/templates/crypto_price.py#L20) and append `&api_key={your_api_key}` at the end of this inside each script as documented [here](https://min-api.cryptocompare.com/documentation) 

3. Significant structural changes to this application (this is more a note for myself) that would call all coins for each currency in a single  `data/pricemultifull` call (as documented [here](https://hexdocs.pm/crypto_compare/CryptoCompare.html#pricemultifull/3)) I'm not sure this would be possible, but would remove the multiplier by the number of crypto's being used.

Hope this helps matters 😄

**Comment by awkwardsky** [comment]
Hey @chrislennon
>1. ...

I reducing the refresh rate, to 
"Always run when widget becomes visible."
&
"Execute script every 3600 seconds."

My widget setting is not always visible, it's visibility when i pressed the specific key.
but I'm not sure 
the calls calculate in one day = my all pressed times * number of coin pairing widgets
or
the calls calculate in one day = (my all pressed times + 24 times) * number of coin pairing widgets
which one it correct? or the other? 



> 2. I see that CryptoCompare has a [free tier ](https://min-api.cryptocompare.com/pricing) on their private API, this seems to increase the monthly cap from 50k to 100k
>    
>    * If you wanted to use this after obtaining an API key you would need to add it into the URL inside the script that BTT uses to call the API. In essence you would be looking for [this line](https://github.com/chrislennon/Crypto-Touchbar-App/blob/master/templates/crypto_price.py#L20) and append `&api_key={your_api_key}` at the end of this inside each script as documented [here](https://min-api.cryptocompare.com/documentation)

it's working haha!
Your "getting back" is fast enough for me, don’t worry about it.  thank a lots.
```
        url = "https://min-api.cryptocompare.com/data/pricemultifull?fsyms={}&tsyms={}&api_key=10817XXX....".format(coin_ticker, fiat_ticker)
```

>3. ...

this issue i have no idea how to refactor the script


Thank you for taking your valuable time.
