### ISSUE TITLE
Displaying Digital Coin Values on Touch Bar Screen

### ISSUE THREAD

**Issue by HoneyGoodspeed** [chrislennon/Crypto-Touchbar-App#101]
Hi Chris,

Love the app. My apologies for being a total newbie here. I currently use the btt app to display bitcoin, ethereal and bitcoin cash on my touch bar. I want to add dogecoin. I thought it would be as simple as copying the information over from one of the coins that works and replacing the code with DOGE but I can not get it to display correctly only my Touch Bar. Any help you can offer would be greatly appreciated. 

Screenshots of altered code and Touch Bar outcome. 

<img width="516" alt="Screen Shot 2021-04-16 at 7 36 07 PM" src="https://user-images.githubusercontent.com/82684887/115094315-16aef500-9eeb-11eb-9fa9-03ea4fee40df.png">
<img width="1004" alt="Touch Bar Shot 2021-04-16 at 7 35 47 PM" src="https://user-images.githubusercontent.com/82684887/115094317-17478b80-9eeb-11eb-9b16-96550d39b11f.png">

**Comment by chrislennon** [comment]
Hey @HoneyGoodspeed I too thought you could have added doge by changing the code - I think that is all that changes when you export it from the tool, To double check could you try exporting dogecoin straight from the [webapp](https://chrislennon.github.io/Crypto-Touchbar-App/)? 

 You may need to search for this in the bar below as for some reason its not listed on the top 😅 
 
![image](https://user-images.githubusercontent.com/9197696/115096424-51358380-9f25-11eb-80cb-0d402409035e.png)

If that doesn't work when imported let me know I'll test it out a bit further

**Comment by HoneyGoodspeed** [comment]
Thanks for your amazingly fast response with easy and quick fix. Thank you! Thank you!

**Comment by chrislennon** [comment]
Hey @HoneyGoodspeed - great to hear that this worked for you, and don't worry no issue about being a newbie here!

P.S. - If you customised that doge icon, looks great 😄 

![image](https://user-images.githubusercontent.com/9197696/115117210-bfb62800-9f9d-11eb-969c-6007639d14f7.png)
