### ISSUE TITLE
Traceback (most recent call last) Error on CryptoTouch Bar

### ISSUE THREAD

**Issue by JD-007** [chrislennon/Crypto-Touchbar-App#102]
Hey Clennon! I just bought the membership for Better Touch Tools only for use of your CryptoTouchBar. but it has been always breaking, I updated the latest version but still am facing this issue [ Traceback (most recent call last): File "<string>', line 25, in <module>]. I think something wrong here in this code line, can you please make a patch fix! THanks

**Comment by chrislennon** [comment]
Hey @JD-007 thanks for reaching out - from some similar reports I believe this typically comes from issues around the APIs rate limiting. If you can check through the details of #100  specifically the directions to check the CryptoCompare API correctly, believe that will show us the error

**Comment by JD-007** [comment]
Thanks for the prompt reply!  I'll look into this now!  I have just signed
up & got the API key, Now I will look forward to BTT app so where I can
replace the API Key,  Should I have to change API Key for each Coin
script?  Thanks mate

**Comment by JD-007** [comment]
[image: image.png]

I have just reached out here but I don't know where to add api key?
        url = "
https://min-api.cryptocompare.com/data/pricemultifull?fsyms={}&tsyms={}".format(coin_ticker,
fiat_ticker) <== Right here at the end or after &tsysm={}"  -

Thanks

**Comment by chrislennon** [comment]
Hey @JD-007 unfortunately until I make any changes for users to have the script template append in a users API key (if they chose so) it would be a manual addition to each script.

I covered some steps to do so [here](https://github.com/chrislennon/Crypto-Touchbar-App/issues/100#issuecomment-803287084) and the other users [reply](https://github.com/chrislennon/Crypto-Touchbar-App/issues/100#issuecomment-803731016) should give you a good heads up on where to add this.

**Comment by JD-007** [comment]
Wow!   Thanks mate!  it's working now,  I just copied that piece of code
with that exact line & edited it with the API on my own, Now it's all
working, though I was using the same line code still I was getting the same
error, it's working now all good!   I'll edit all the scripts & yea one
more thing!   For how long this API will work?  should I have to generate
again new API key once it has reached its limit?   And Thanks for your
great support & work, this TouchBar really saves time!

**Comment by chrislennon** [comment]
@JD-007 believe your API key itself will be valid 'forever' and wont need to regenerate it. however you will likely encounter the error again if you reach [their limits](https://min-api.cryptocompare.com/pricing)

**Comment by JD-007** [comment]
Yea sure!   If I reach the limits then I'll generate the NEW API again!   Thanks for your time mate!   have a nice day.
