### ISSUE TITLE
KeyError: 'RAW'

### ISSUE THREAD

**Issue by SemElVik** [chrislennon/Crypto-Touchbar-App#106]
Traceback (most recent call last):
  File "<string*>", line 25, in <module*>
KeyError: 'RAW'

scrypt - [KeyErr.txt](https://github.com/chrislennon/Crypto-Touchbar-App/files/8105007/KeyErr.txt)

 
`12.2.1 (21D62) Monterey`

stopped working a couple of days ago.
I looked at the closed `issue`, but I'm not sure if I see a solution there

**Comment by chrislennon** [comment]
Hey @SemElVik, you probably want to check out the conversation in #100 I think this error usually occurs when you are hitting CryptoCompare's API limits. There are some steps to check in that issue.

Let me know if you need any assistance

**Comment by SemElVik** [comment]
if you are talking about it, then it does not help

![2022-02-21_02-09-21](https://user-images.githubusercontent.com/27207809/154868519-37322f58-4010-4c52-9f15-0d7b76ec4bcb.png)

**Comment by chrislennon** [comment]
This comment should cover it, it looks like you need to include the apikey inside the "   " before the .format()

https://github.com/chrislennon/Crypto-Touchbar-App/issues/100#issuecomment-803731016

i.e.
```
url = "https://min-api.cryptocompare.com/data/pricemultifull?fsyms={}&tsyms={}&api_key=10817XXX....".format(coin_ticker, fiat_ticker)
```

**Comment by SemElVik** [comment]
definitely not. I tried this too
![2022-02-21_02-18-50](https://user-images.githubusercontent.com/27207809/154868810-c7045b60-53ea-427d-8070-beffcb2569a7.png)
.

**Comment by chrislennon** [comment]
That did actually fix it as you have another error (line 20 passed, new error is on line 22).

That error is python complaining that the indentation does not match the previous line.

I'm unsure what exactly changed but if you create a fresh export from the site and only modify the url line as you did, it should work.

**Comment by SemElVik** [comment]
ok   
thx

**Comment by SemElVik** [comment]
yes it worked

thanks!
