### ISSUE TITLE
Traceback error?

### ISSUE THREAD

**Issue by bottlebug** [chrislennon/Crypto-Touchbar-App#107]
Hi there. I've been using the Crypto Touch Bar for a few months now and suddenly I am getting this error.

`Traceback (most recent call last):
  File "<string>", line 25, in <module>
KeyError: 'RAW'`

**Comment by chrislennon** [comment]
Hey @bottlebug - you may want to check out [this comment](https://github.com/chrislennon/Crypto-Touchbar-App/issues/100#issuecomment-803731016) on #100 - also very recently #106 

Let me know if that fixes it/elaborates on the issue or if you have any other questions
