### ISSUE TITLE
Widget Stopped Working with latest macOS Monterey 21E230

### ISSUE THREAD

**Issue by akhiltaneja** [chrislennon/Crypto-Touchbar-App#108]
Widget Stopped Working with latest macOS Monterey 21E230.

All I can see is abnormally expanded widgets with no price.

**Comment by hifirestone** [comment]
This broke for me when upgrading from macOS Monterey 12.0.1 to 12.3.

I don't know much about this but i think it has something to do with the fact that it needs to be updated to use Python3 in Monterey which, [according to this page](https://docs.python.org/3/whatsnew/3.0.html):

> String literals no longer support a leading `u` or `U`.

The error the script returns when run after setting the launch path to `/usr/bin/python3` is:
>`File "<string>", line 87`
>`    except urllib2.URLError, e:`
> `                          ^`
>`SyntaxError: invalid syntax`

Not actually knowing python myself, I have no idea how to fix it.

**Comment by chrislennon** [comment]
Thanks @akhiltaneja & @hifirestone - I knew the day would finally come 😢 

We were talking about switching over to a non python execution based system for two reasons, as you note - finally deprecating 2.x and additionally python doesn't ship without additional downloads etc now.

I'll see what I can do to make it 3.x compatible (though backwards compatibility might be.... 'fun').

The longterm fix is likely to switch over to using @fifafu's JS in-built implementation to BTT.

**Comment by fifafu** [comment]
I think I'll be create a merge request for the JS implementation next week. I have been running it on my machine for the last two months and it's stable :-)

If necessary I think installing Python 2.x is still easily possible https://stackoverflow.com/a/71592278

**Comment by chrislennon** [comment]
I'll see whats needed to keep the fallback of python2 with a fall 'forward' to v3 in the mean time, if I recall, its just templating on the python side so I should in theory just be able to do a quick switcheroo

**Comment by chrislennon** [comment]
hey again @akhiltaneja & @hifirestone  - I just pushed a quick hot fix which may workaround this for now. Added a new template and python selection for 2/3.

Let me know if it helps until we have a better route forward for this.

**Comment by akhiltaneja** [comment]
> 

Hey, Thanks, @chrislennon I tried the new Python 3 implementation, But unfortunately, the issue persists.

**Comment by chrislennon** [comment]
@akhiltaneja Do you happen to have an error or output (maybe running it directly from inside BTT?) for me to work with. All the 2.x references should be gone from @hifirestone's comment, just want to check you aren't running into something like #100 or another unrelated issue.

**Comment by akhiltaneja** [comment]
> @akhiltaneja Do you happen to have an error or output (maybe running it directly from inside BTT?) for me to work with. All the 2.x references should be gone from @hifirestone's comment, just want to check you aren't running into something like #100 or another unrelated issue.

It is showing something like this SC: 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/14196666/161154543-6392aba5-16e9-48eb-a160-e10625e848c9.png">

**Comment by chrislennon** [comment]
Very curious, I don't seem to be able to see any error, is there anything in the 'result' section when you click 'run script' inside BTT?

<img width="1399" alt="Screenshot 2022-03-31 at 22 48 37" src="https://user-images.githubusercontent.com/9197696/161155341-eb198b53-e6ad-4344-b548-c135d5ac8d3d.png">

**Comment by hifirestone** [comment]
@chrislennon I really don't want to speak out of turn here as I'm no expert but are you also running macOS 12.3? Apple has deprecated Python 2 entirely and I do not even have it located in my /usr/bin directory anymore. Only python3 is now there.

<img width="726" alt="Screen Shot 2022-03-31 at 16 55 43" src="https://user-images.githubusercontent.com/51712046/161155857-4f0b35f6-bcd8-416c-85c5-ad41636aadb8.png">

Sorry if this is irrelevant.

**Comment by chrislennon** [comment]
Hey @hifirestone - I'm not actually running 12.3 but I have both versions of python to check on. I'm using two outputs (generated from the site and saved as a file by copying the code from inside BTT) and running `/usr/bin/python` for the v2 and `/usr/bin/python3` for the v3 one.

Have you tried exporting a new python v3 one from [the site](https://chrislennon.github.io/Crypto-Touchbar-App/)? I'm really curious to see what errors we are getting - if you can post some outputs like mentioned on [the post above](https://github.com/chrislennon/Crypto-Touchbar-App/issues/108#issuecomment-1085160822) I should be able to figure out whats going on or what I missed. 😄

**Comment by hifirestone** [comment]
Without changing the launch path:
launch path not accessible
(
	0   CoreFoundation                      0x0000000181fdeb08 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x0000000181d29e14 objc_exception_throw + 60
	2   Foundation                          0x0000000182ebbecc -[NSConcreteTask launchWithDictionary:error:] + 4608
	3   BetterTouchToolShellScriptRunner    0x0000000100c6f374 -[BetterTouchToolShellScriptRunner runShellTaskWithLaunchPath:parameters:script:environmentVariables:presetPath:withReply:] + 1836
	4   CoreFoundation                      0x0000000181f3f684 __invoking___ + 148
	5   CoreFoundation                      0x0000000181f3f4fc -[NSInvocation invoke] + 468
	6   Foundation                          0x0000000182e9a0dc __NSXPCCONNECTION_IS_CALLING_OUT_TO_EXPORTED_OBJECT__ + 24
	7   Foundation                          0x0000000182e42820 -[NSXPCConnection _decodeAndInvokeMessageWithEvent:flags:] + 1392
	8   Foundation                          0x0000000182df6d28 message_handler + 228
	9   libxpc.dylib                        0x0000000181bc91bc _xpc_connection_call_event_handler + 152
	10  libxpc.dylib                        0x0000000181bc7bf8 _xpc_connection_mach_event + 1360
	11  libdispatch.dylib                   0x0000000181cce288 _dispatch_client_callout4 + 20
	12  libdispatch.dylib                   0x0000000181cea53c _dispatch_mach_msg_invoke + 464
	13  libdispatch.dylib                   0x0000000181cd5784 _dispatch_lane_serial_drain + 376
	14  libdispatch.dylib                   0x0000000181ceb25c _dispatch_mach_invoke + 456
	15  libdispatch.dylib                   0x0000000181cd5784 _dispatch_lane_serial_drain + 376
	16  libdispatch.dylib                   0x0000000181cd6438 _dispatch_lane_invoke + 444
	17  libdispatch.dylib                   0x0000000181ce0c98 _dispatch_workloop_worker_thread + 648
	18  libsystem_pthread.dylib             0x0000000181e8e360 _pthread_wqthread + 288
	19  libsystem_pthread.dylib             0x0000000181e8d080 start_wqthread + 8
)

After changing the launch path to python3:

<string>:43: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:45: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:47: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:49: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:51: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:53: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:55: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:57: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:60: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:79: SyntaxWarning: "is" with a literal. Did you mean "=="?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'urllib2'

I'm not sure if I have this running correctly anymore, in general. Here's what it looks like locally:
<img width="1440" alt="Screen Shot 2022-03-31 at 18 13 00" src="https://user-images.githubusercontent.com/51712046/161164346-a63b30cb-5d5d-4b3b-9d0c-513ad8a41af5.png">

**Comment by chrislennon** [comment]
@hifirestone Did you try a new export from [the website](https://chrislennon.github.io/Crypto-Touchbar-App/) I uploaded a couple of hours ago? you will need to select python 3 from the new dropdown, all these errors/warnings should be fixed 🤞

**Comment by hifirestone** [comment]
Sorry about that, I hadn't. That webpage's workflow is very helpful, thanks.

However when I import there is no default action in the trigger when adding it via JSON or direct import to BTT. Shouldn't there be an "Execute Shell Script/Task" action?

I am not able to see the code to run the script. Am I simply missing a step?

I've added the Execute Shell Script/Task action and copied the code from https://github.com/chrislennon/Crypto-Touchbar-App/blob/master/templates/crypto_price.py

Without changing the launch path, I get:
>launch path not accessible
(
	0   CoreFoundation                      0x0000000181fdeb08 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x0000000181d29e14 objc_exception_throw + 60
	2   Foundation                          0x0000000182ebbecc -[NSConcreteTask launchWithDictionary:error:] + 4608
	3   BetterTouchToolShellScriptRunner    0x0000000104ebb374 -[BetterTouchToolShellScriptRunner runShellTaskWithLaunchPath:parameters:script:environmentVariables:presetPath:withReply:] + 1836
	4   CoreFoundation                      0x0000000181f3f684 __invoking___ + 148
	5   CoreFoundation                      0x0000000181f3f4fc -[NSInvocation invoke] + 468
	6   Foundation                          0x0000000182e9a0dc __NSXPCCONNECTION_IS_CALLING_OUT_TO_EXPORTED_OBJECT__ + 24
	7   Foundation                          0x0000000182e42820 -[NSXPCConnection _decodeAndInvokeMessageWithEvent:flags:] + 1392
	8   Foundation                          0x0000000182df6d28 message_handler + 228
	9   libxpc.dylib                        0x0000000181bc91bc _xpc_connection_call_event_handler + 152
	10  libxpc.dylib                        0x0000000181bc7bf8 _xpc_connection_mach_event + 1360
	11  libdispatch.dylib                   0x0000000181cce288 _dispatch_client_callout4 + 20
	12  libdispatch.dylib                   0x0000000181cea53c _dispatch_mach_msg_invoke + 464
	13  libdispatch.dylib                   0x0000000181cd5784 _dispatch_lane_serial_drain + 376
	14  libdispatch.dylib                   0x0000000181ceb25c _dispatch_mach_invoke + 456
	15  libdispatch.dylib                   0x0000000181cd5784 _dispatch_lane_serial_drain + 376
	16  libdispatch.dylib                   0x0000000181cd6438 _dispatch_lane_invoke + 444
	17  libdispatch.dylib                   0x0000000181ce0c98 _dispatch_workloop_worker_thread + 648
	18  libsystem_pthread.dylib             0x0000000181e8e360 _pthread_wqthread + 288
	19  libsystem_pthread.dy

Changing the launch path to /usr/bin/python3:

><string>:45: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:47: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:49: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:51: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:53: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:55: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:57: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:59: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:62: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:81: SyntaxWarning: "is" with a literal. Did you mean "=="?
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'urllib2'

Here's a screenshot:

<img width="1440" alt="Screen Shot 2022-03-31 at 18 52 36" src="https://user-images.githubusercontent.com/51712046/161167920-bdba16ec-bdb1-4068-b30a-537b3af71125.png">

**Comment by chrislennon** [comment]
@hifirestone the files in `https://github.com/chrislennon/Crypto-Touchbar-App/blob/master/templates/...` are just templates they won't directly work when added as a script inside BTT. Though if you wanted to try this you should use crypto_price3.py for the python3 stuff.

I think you are right the code only runs on time interval (not when initially shown/executed) - think this has been a long standing bug.

Interestingly I just noticed what is up. On my python3 one (using ADA as a random example) I updated the usage of python3 in the script, but I didn't modify it in the BTT launch config (green in screenshot).

<img width="1449" alt="Screenshot 2022-04-01 at 01 19 08" src="https://user-images.githubusercontent.com/9197696/161171248-e590be9d-aa9b-4e99-baeb-ae6c4102fd90.png">

Let me see if I can find a really quick fix for that now otherwise I'll crack it tomorrow

**Comment by chrislennon** [comment]
@akhiltaneja @hifirestone  - think I realised what was missed, needed to change it in one more place (see above).

You should be able to generate from the site again and the launch path should now reflect /usr/bin/python3 (and not just in the scripts shebang - oooooops 😅 )

**Comment by akhiltaneja** [comment]
> 

I did it again, now it shows "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun"

**Comment by chrislennon** [comment]
Thanks for checking @akhiltaneja - this looks like it's trying to install python3 and wanting to use the developer tools to do so.

May want to check out this https://apple.stackexchange.com/a/254381

You will likely want to run `/usr/bin/python3` in the terminal once to check it's working after it's there

I hate how Apple has changed this 🥲

We'll be moving away from python at some point but installing python like above or python2 as @fifafu should hopefully get things on track

**Comment by hifirestone** [comment]
@chrislennon It appears to be working just fine now! As to your point about not running until the time interval is met, there's a button I just noticed that is off by default after import:
<img width="407" alt="Screen Shot 2022-04-01 at 08 57 54" src="https://user-images.githubusercontent.com/51712046/161278298-bde7c133-6019-4113-b0b6-43ccecbc6f56.png">

Once this is checked, the script runs immediately every time the trigger is updated. Can your website export have this button set to "on" by default?

**Comment by chrislennon** [comment]
Added the defaulting to run when first visible just now.

Will close this out just now but do let me know if you see any bugs or improvements. We'll continue to figure out a better route for removing the python dependancy entirely.
