### ISSUE TITLE
Currency graphs

### ISSUE THREAD

**Issue by BJJLangedijk** [chrislennon/Crypto-Touchbar-App#49]
Show the currency graph/trend with some meaningful values attached.

![pasted image at 2017_12_29 11_47 am](https://user-images.githubusercontent.com/1398409/34435536-ad6ed70c-ec8e-11e7-9be5-962dbe561739.png)

* Trend of coin
* Percentage of change
* Actual coin value change based on the currency set for that coin

This graph could be shown whenever the user clicks on a coin.

**Comment by chrislennon** [comment]
Idea looks very nice indeed. Some initial thoughts.
As we are (currently) outputting to BetterTouchTool, the options we have are:
 
- build these charts in native applescript... (lol i doubt it)
- `do shell script` and do this in bash, doubtful
- `do shell script python -c 'import....'` and offload the work into python (or any other tool), I think this approach has more legs - however we will likely end up bringing in external dependancies such as [plotly](https://plot.ly/python/candlestick-charts/) - no problem for devs, but lets keep non-tech users in mind too.

**Comment by chrislennon** [comment]
Been thinking about this again, and whilst I like the idea I'm not sure we will be able to implement it - at least inside BetterTouchTool, if we ever took the plunge of building a native app, would be a different story

The problem I think resides within the fact we would need to make use of the 'Icon' of the touch bar to show the chart (see [example attached](https://github.com/chrislennon/Crypto-Touchbar-App/files/1594531/TestGraph.json.txt)), however we would only be able to generate this at export/import time not programatically from the API response.

_A side thought_ - maybe we could use a 'graph font' to output the candles, but I don't think this is supported inside BTT either at the moment.

@fifafu - any thoughts?
