### ISSUE TITLE
Remove applescript logic

### ISSUE THREAD

**Issue by chrislennon** [chrislennon/Crypto-Touchbar-App#63]
BTT looks to be moving towards allowing shell script directly rather than looping it though applescript - https://twitter.com/boastr_net/status/952544253628076032.

This should provide us a few benefits:
- no more applescript - hell yeah! :tada:
- better handling of numbers and formats
- better access to other binaries and OS functions without jumping though loops

Thanks @fifafu! this is awesome - any approximation on the alpha -> stable date?

**Comment by fifafu** [comment]
Sometime this week :-)

**Comment by chrislennon** [comment]
alright, i'll get to work this week too and strip out the apple"script" 😉

**Comment by fifafu** [comment]
Awesome, this should improve performance a lot.
I need to fix one remaining issue with the json export/import, then everything necessary should work. I'll do that later today.

**Comment by fifafu** [comment]
2.324 alpha is now online and should contain everything necessary. One thing that might also be interesting is the possibility to import via btt:// links with base64 encoded json data like this:

btt://jsonimport/ew0KICAiQlRUV2lkZ2V0TmFtZSIgOiAiQXBwbGUgU3RvY2sgUHJpY2UiLA0KICAiQlRUVHJpZ2dlclR5cGUiIDogNjQyLA0KICAiQlRUVHJpZ2dlclR5cGVEZXNjcmlwdGlvbiIgOiAiU2hlbGwgU2NyaXB0IFwvIFRhc2sgV2lkZ2V0IiwNCiAgIkJUVFRyaWdnZXJDbGFzcyIgOiAiQlRUVHJpZ2dlclR5cGVUb3VjaEJhciIsDQogICJCVFRQcmVkZWZpbmVkQWN0aW9uVHlwZSIgOiAtMSwNCiAgIkJUVFByZWRlZmluZWRBY3Rpb25OYW1lIiA6ICJObyBBY3Rpb24iLA0KICAiQlRUU2hlbGxTY3JpcHRXaWRnZXRHZXN0dXJlQ29uZmlnIiA6ICJcL1VzZXJzXC9hbmRpXC8ubnZtXC92ZXJzaW9uc1wvbm9kZVwvdjguNC4wXC9iaW5cL25vZGU6OjotZSIsDQogICJCVFRFbmFibGVkIiA6IDEsDQogICJCVFRPcmRlciIgOiA1LA0KICAiQlRUVHJpZ2dlckNvbmZpZyIgOiB7DQogICAgIkJUVFRvdWNoQmFySXRlbUljb25IZWlnaHQiIDogMjIsDQogICAgIkJUVFRvdWNoQmFySXRlbUljb25XaWR0aCIgOiAyMiwNCiAgICAiQlRUVG91Y2hCYXJJdGVtUGFkZGluZyIgOiAwLA0KICAgICJCVFRUb3VjaEJhckZyZWVTcGFjZUFmdGVyQnV0dG9uIiA6ICI1LjAwMDAwMCIsDQogICAgIkJUVFRvdWNoQmFyQnV0dG9uQ29sb3IiIDogIjQzLjgzMDE2MiwgMTU1LjkxNzEzMiwgNDUuMjg2NzIwLCAyNTUuMDAwMDAwIiwNCiAgICAiQlRUVG91Y2hCYXJBbHdheXNTaG93QnV0dG9uIiA6ICIwIiwNCiAgICAiQlRUVG91Y2hCYXJBcHBsZVNjcmlwdFN0cmluZyIgOiAiY29uc3QgaHR0cHMgPSByZXF1aXJlKFwiaHR0cHNcIik7XG5jb25zdCB1cmwgPSBcImh0dHBzOlwvXC9maW5hbmNlLmdvb2dsZS5jb21cL2ZpbmFuY2U/cT1BQVBMJm91dHB1dD1qc29uXCI7XG5odHRwcy5nZXQodXJsLCByZXMgPT4ge1xuICBsZXQgYm9keSA9IFwiXCI7ICByZXMub24oXCJkYXRhXCIsIGRhdGEgPT4geyBib2R5ICs9IGRhdGE7IH0pO1xuICByZXMub24oXCJlbmRcIiwgKCkgPT4ge1xuICAgIGJvZHkgPSBKU09OLnBhcnNlKGJvZHkuc2xpY2UoNCkpOyBcL1wvIHRoaXMgaXMgYmVjYXVzZSB0aGUgZmluYW5jZSBhcGkgYWx3YXlzIHJldHVybnMganNvbiB3aXRoIHNvbWUgcHJlZml4XG5pZihib2R5KVxuICAgIGNvbnNvbGUubG9nKCdBQVBMICcgICsgYm9keVswXVsnbCddICsgJyAoJyAgKyBib2R5WzBdWydjJ10gKyAnKScpO1xuICB9KTtcbn0pOyIsDQogICAgIkJUVFRvdWNoQmFyQ29sb3JSZWdleCIgOiAiLSIsDQogICAgIkJUVFRvdWNoQmFyQWx0ZXJuYXRlQmFja2dyb3VuZENvbG9yIiA6ICIxNDAuODY2MDI2LCA1LjAyMDc2OSwgMTUuNTkyMDgxLCAyNTUuMDAwMDAwIiwNCiAgICAiQlRUVG91Y2hCYXJTY3JpcHRVcGRhdGVJbnRlcnZhbCIgOiA2NS45NDgyMTkyOTkzMTY0MDYNCiAgfQ0KfQ==

**Comment by chrislennon** [comment]
Perfect, updated to the alpha now and will probably start playing with the changes tomorrow.

The Base64 import is interesting indeed! Thanks for letting me know. Will likely include that as an option too.

I assume once imported the script is human readable again? I've seen a few comments on reddit (rightfully) paranoid about the scripts that are embedded, wouldn't like to hide anything from users.

Gave it a quick test - I have only had it work on safari, is it anticipated to work on chrome too? (if you want to shift the alpha bug discussion to your repo, just link me 😉 )

**Comment by fifafu** [comment]
Chrome only allows custom urls via clickable links for some reason, not when entering them in the address bar. (Github didn't allow me to make the link clickable :-))

After importing it is readable again.

I also plan some sort of platform where presets can be shared and where I can mark the ones I checked as "trusted".

**Comment by fifafu** [comment]
This should also work in Chrome via the addressbar:

```
javascript:window.open('btt://jsonimport/ew0KICAiQlRUV2lkZ2V0TmFtZSIgOiAiQXBwbGUgU3RvY2sgUHJpY2UiLA0KICAiQlRUVHJpZ2dlclR5cGUiIDogNjQyLA0KICAiQlRUVHJpZ2dlclR5cGVEZXNjcmlwdGlvbiIgOiAiU2hlbGwgU2NyaXB0IFwvIFRhc2sgV2lkZ2V0IiwNCiAgIkJUVFRyaWdnZXJDbGFzcyIgOiAiQlRUVHJpZ2dlclR5cGVUb3VjaEJhciIsDQogICJCVFRQcmVkZWZpbmVkQWN0aW9uVHlwZSIgOiAtMSwNCiAgIkJUVFByZWRlZmluZWRBY3Rpb25OYW1lIiA6ICJObyBBY3Rpb24iLA0KICAiQlRUU2hlbGxTY3JpcHRXaWRnZXRHZXN0dXJlQ29uZmlnIiA6ICJcL1VzZXJzXC9hbmRpXC8ubnZtXC92ZXJzaW9uc1wvbm9kZVwvdjguNC4wXC9iaW5cL25vZGU6OjotZSIsDQogICJCVFRFbmFibGVkIiA6IDEsDQogICJCVFRPcmRlciIgOiA1LA0KICAiQlRUVHJpZ2dlckNvbmZpZyIgOiB7DQogICAgIkJUVFRvdWNoQmFySXRlbUljb25IZWlnaHQiIDogMjIsDQogICAgIkJUVFRvdWNoQmFySXRlbUljb25XaWR0aCIgOiAyMiwNCiAgICAiQlRUVG91Y2hCYXJJdGVtUGFkZGluZyIgOiAwLA0KICAgICJCVFRUb3VjaEJhckZyZWVTcGFjZUFmdGVyQnV0dG9uIiA6ICI1LjAwMDAwMCIsDQogICAgIkJUVFRvdWNoQmFyQnV0dG9uQ29sb3IiIDogIjQzLjgzMDE2MiwgMTU1LjkxNzEzMiwgNDUuMjg2NzIwLCAyNTUuMDAwMDAwIiwNCiAgICAiQlRUVG91Y2hCYXJBbHdheXNTaG93QnV0dG9uIiA6ICIwIiwNCiAgICAiQlRUVG91Y2hCYXJBcHBsZVNjcmlwdFN0cmluZyIgOiAiY29uc3QgaHR0cHMgPSByZXF1aXJlKFwiaHR0cHNcIik7XG5jb25zdCB1cmwgPSBcImh0dHBzOlwvXC9maW5hbmNlLmdvb2dsZS5jb21cL2ZpbmFuY2U/cT1BQVBMJm91dHB1dD1qc29uXCI7XG5odHRwcy5nZXQodXJsLCByZXMgPT4ge1xuICBsZXQgYm9keSA9IFwiXCI7ICByZXMub24oXCJkYXRhXCIsIGRhdGEgPT4geyBib2R5ICs9IGRhdGE7IH0pO1xuICByZXMub24oXCJlbmRcIiwgKCkgPT4ge1xuICAgIGJvZHkgPSBKU09OLnBhcnNlKGJvZHkuc2xpY2UoNCkpOyBcL1wvIHRoaXMgaXMgYmVjYXVzZSB0aGUgZmluYW5jZSBhcGkgYWx3YXlzIHJldHVybnMganNvbiB3aXRoIHNvbWUgcHJlZml4XG5pZihib2R5KVxuICAgIGNvbnNvbGUubG9nKCdBQVBMICcgICsgYm9keVswXVsnbCddICsgJyAoJyAgKyBib2R5WzBdWydjJ10gKyAnKScpO1xuICB9KTtcbn0pOyIsDQogICAgIkJUVFRvdWNoQmFyQ29sb3JSZWdleCIgOiAiLSIsDQogICAgIkJUVFRvdWNoQmFyQWx0ZXJuYXRlQmFja2dyb3VuZENvbG9yIiA6ICIxNDAuODY2MDI2LCA1LjAyMDc2OSwgMTUuNTkyMDgxLCAyNTUuMDAwMDAwIiwNCiAgICAiQlRUVG91Y2hCYXJTY3JpcHRVcGRhdGVJbnRlcnZhbCIgOiA2NS45NDgyMTkyOTkzMTY0MDYNCiAgfQ0KfQ==');
```

//edit: actually chrome enforces the javascript: part at the beginning of the url to be entered manually, so pasting doesn't work. However it works fine when calling it directly via javascript.

**Comment by chrislennon** [comment]
Love the platform idea, was thinking to approach you with something like that myself.

JS above doesn't work for me, but I get your point on chrome - will add the link import feature for sure 👍

**Comment by chrislennon** [comment]
@fifafu I just attempted to add the `btt://jsonimport` to PR #64, it triggers the import, however nothing is successful (or fails) - just no output or change. 

Is there any method I can use to debug the (I assume failed) import? 

Currently #64 will `console.log` out the base64 string, after a decode and save to file this imports correctly, so I'm unsure where the issue sits.

Cheers!

**Comment by fifafu** [comment]
@chrislennon ah sorry, it currently doesn't allow to import complete presets - only apps or triggers like this (can also be an array of triggers):

```
{
  "BTTWidgetName" : "Apple Stock Price",
  "BTTTriggerType" : 642,
  "BTTTriggerTypeDescription" : "Shell Script \/ Task Widget",
  "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
  "BTTPredefinedActionType" : -1,
  "BTTPredefinedActionName" : "No Action",
  "BTTShellScriptWidgetGestureConfig" : "\/Users\/andi\/.nvm\/versions\/node\/v8.4.0\/bin\/node:::-e",
  "BTTEnabled" : 1,
  "BTTOrder" : 5,
  "BTTTriggerConfig" : {
    "BTTTouchBarItemIconHeight" : 22,
    "BTTTouchBarItemIconWidth" : 22,
    "BTTTouchBarItemPadding" : 0,
    "BTTTouchBarFreeSpaceAfterButton" : "5.000000",
    "BTTTouchBarButtonColor" : "43.830162, 155.917132, 45.286720, 255.000000",
    "BTTTouchBarAlwaysShowButton" : "0",
    "BTTTouchBarAppleScriptString" : "const https = require(\"https\");\nconst url = \"https:\/\/finance.google.com\/finance?q=AAPL&output=json\";\nhttps.get(url, res => {\n  let body = \"\";  res.on(\"data\", data => { body += data; });\n  res.on(\"end\", () => {\n    body = JSON.parse(body.slice(4)); \/\/ this is because the finance api always returns json with some prefix\nif(body)\n    console.log('AAPL '  + body[0]['l'] + ' ('  + body[0]['c'] + ')');\n  });\n});",
    "BTTTouchBarColorRegex" : "-",
    "BTTTouchBarAlternateBackgroundColor" : "140.866026, 5.020769, 15.592081, 255.000000",
    "BTTTouchBarScriptUpdateInterval" : 65.948219299316406
  }
}
````
However I'll add preset import before the final release, so this should be ok.

**Comment by fifafu** [comment]
I have just uploaded another alpha and your import button now works perfectly :-)

I'll probably ready the public release tomorrow. I'll mention your great project in the release notes if that's ok.

**Comment by chrislennon** [comment]
Awesome! Gave it a quick test myself and looks fairly good, looks like I have a small issue on the emoji output when grouping as a button, and the currency symbol gets removed/mangled. 

This only happens on the `btt://` import style - likely something to do with loss of utf8 and base64 conversions back and forth.

Will try to fix it soon - Will merge when you release and I've attempted a fix 🤓 

As for the mentioning of the project - sure! Would be happy to get more users/features/suggestions 😄 I'm sure they're are many other lingering bugs too 😅

**Comment by fifafu** [comment]
The encoding issue seems to be on BTTs side. I'll upload another little fix in a few minutes.

**Comment by chrislennon** [comment]
I suspected it might be but wanted to dig into it further before pointing fingers 👉 

If you fix it, you're a ⭐️

**Comment by fifafu** [comment]
I have now publicly released v2.331 and will slowly be rolling it out :-)
(Let's see whether everything works ok, otherwise I'll release another update tomorrow)

**Comment by chrislennon** [comment]
#64 is working for me on stable v2.331 
Seems to be faster too 👍 

Merging and deploying now :shipit:

**Comment by chrislennon** [comment]
@fifafu Thanks very much for this, thats it now live! 

I noticed a couple of silly mistakes on my end which will hotfix out just now 🤐
