### ISSUE TITLE
Does like £ or 2 decimal places in Pounds Sterling

### ISSUE THREAD

**Issue by TheBartoMan** [chrislennon/Crypto-Touchbar-App#75]
If you choose pounds sterling you get errors. It doesn't like the £ and also doesn't like if you set it to 2 decimal places.

**Comment by chrislennon** [comment]
Hey, yeah I've just replicated this. Looks like its mainly effecting the lower value cryptos, bitcoin works with those settings but many others don't.

For now changing the settings to infinite decimals seems to fix it. I will report back here with a fix that should fix the issues with formatting somewhat soon.

**Comment by chrislennon** [comment]
This issue has been closed as part of #76.

After moving to python away from applescript there were a few issues regarding formatting options. This PR should resolve the issues going forward, please let me know if it works and of course if the issue continues reopen this issue and we can debug further.
