### ISSUE TITLE
show market cap

### ISSUE THREAD

**Issue by TomOnGit** [chrislennon/Crypto-Touchbar-App#79]
First; Thanks for making this!

Would be great if market cap would be included.

**Comment by chrislennon** [comment]
@TomOnGit - No problem, thanks for using it!

My development is somewhat constrained as I no longer have a device with a touchbar 😅 but I believe this would be no problem to add (can see the 'MKTCAP' value in the [api](https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC&tsyms=USD) I use).

Just to be clear of the request would you suggest/prefer something like:

`$9100 ($154,136,802,283.2)` i.e. price (market-cap)
or something just stating the market cap of the coins selected?
