### ISSUE TITLE
Keep last price when no Internet connection

### ISSUE THREAD

**Issue by Marubozu** [chrislennon/Crypto-Touchbar-App#80]
Hi, thanks for such cool feature!

When a computer is not connected to Internet (bus, plane, etc.) or the connection drops, the currency label shows a long error message instead of the currency details (price, arrows, etc.).

Would it be possible to add a feature that would keep displayed the last price which was available before the connection dropped rather than displaying an error message that takes the whole Touch Bar?

Thank you :)

**Comment by chrislennon** [comment]
@Marubozu no problem, thanks for using it!

Yeah the errors received when offline aren't the nicest looking 😭  (as a side note this should probably be corrected regardless of this issue)

I will need to have a think on this one - my first thoughts - whilst I like the outcome, showing the last available price. I have two points I would need to work out before pushing it live:

- [x] Writing/reading to/from disk - whilst not a big issue, will need to have a think about how I implement it sensibly
- [x] How to handle false positive errors, i.e. last price is still shown but there is actually an error receiving a new price.

I'll have a think and see if there is a good way of approaching this 👍

**Comment by Marubozu** [comment]
Hi Chris, I was sure it would be more complex to develop that it seems! If I can be of any help though let me know, I'll be happy to help you.

**Comment by chrislennon** [comment]
Better late than never I guess... A recent refactor made this much simpler to implement.

Need to do some double checking but when #85 merges this should enable a limited form of caching to prevent errors whilst offline.
