### ISSUE TITLE
Cardano icon not showing

### ISSUE THREAD

**Issue by jadwahab** [chrislennon/Crypto-Touchbar-App#82]
Thanks for making this! Looks nicer and has more options than the previous one I had.
Just one issue, the ADA icon is not showing up and I don't how to fix it, any ideas?

**Comment by chrislennon** [comment]
@jadwahab thank you for using it!

I see the cardano/ADA icon in the main selection screen, do you mean when you export it to BetterTouchTool you don't see the icon?

<img width="212" alt="ada" src="https://user-images.githubusercontent.com/9197696/38460398-37efcbf2-3ab9-11e8-8ab4-e2e2c004043b.PNG">

**Comment by jadwahab** [comment]
Yupp, when I export it to BetterTouchTool it shows up as a white circle like in the pic below:
![img_5357](https://user-images.githubusercontent.com/15110087/38460426-5e790dea-3ab1-11e8-805c-4a53ff08e5cc.JPG)

**Comment by chrislennon** [comment]
thanks for confirming this. I don't have a touch bar currently to test with. 

I believe it could be related to this issue though https://github.com/fifafu/BetterTouchTool/issues/1034

I'm not 100% sure on a solution, but you could try changing the icon to be non-black/non-white, that may fix the issue

**Comment by chrislennon** [comment]
Closing stale - though I believe this issue still persists but is an issue with BTT
