### ISSUE TITLE
Adding A Coin Icon

### ISSUE THREAD

**Issue by LegalPrimes** [chrislennon/Crypto-Touchbar-App#84]
The instructions for adding a custom coin icon are missing. Please add instructions so we can add our own coins.

**Comment by chrislennon** [comment]
You are totally correct - I ended up travelling before I completed parts of my refactor.
Will probably complete this in the next 2-4 days.

In the mean time here are some very brief instructions.

To temporarily  a coin (listed in the list of 2000+ coins, but with no icon) 
- Add an entry to the [data/coins.js](https://github.com/chrislennon/Crypto-Touchbar-App/blob/master/data/coins.js) file.
  - for an example of a custom icon Binance Coin was one that was added in this way [line 147](https://github.com/chrislennon/Crypto-Touchbar-App/blob/master/data/coins.js#L147)
- Add an SVG image of the coin to the [img/temp](https://github.com/chrislennon/Crypto-Touchbar-App/tree/master/img/temp) folder.

If you wish a more complete solution I would also suggest checking and submitting the coin to [allienworks/cryptocoins](https://github.com/allienworks/cryptocoins). That is where I inherit my main source of coin icons from.

**Comment by chrislennon** [comment]
@LegalPrimes I have updated the [wiki page](https://github.com/chrislennon/Crypto-Touchbar-App/wiki/Adding-A-Coin-Icon) to reflect the steps for adding custom icons - manually, in the upstream icon repository and this project.

Let me know if I can assist further.
