### ISSUE TITLE
Add round parameter

### ISSUE THREAD

**Issue by otaviobonder** [chrislennon/Crypto-Touchbar-App#86]
Hi, I think it's useful to add a setting in the webpage to let the user customise the rounding parameter. I've modified the code to round the % to 2 decimals:

```
elif (output_type is "current-percentage"):
            output = fiat_symbol + current + " (" + str(round((((raw_current - raw_opening) / raw_current) * 100), 2)) + "%)"
```

I've made this because I thought it was strange to have the percentage changing from 1 to 1%.

Thanks and nice work!

**Comment by chrislennon** [comment]
Thanks for the suggestion @otaviobps I have added it into #87 which should be merged shortly.
