### ISSUE TITLE
Using MXN doesn't work

### ISSUE THREAD

**Issue by Angel-Avila** [chrislennon/Crypto-Touchbar-App#89]
Using Mexican peso as the currency throws an error:

`Traceback (most recent call last):
  File "<string>", line 25, in <module>
KeyError: 'BTC'`

That message is thrown after doing:
> Advanced settings -> Run script

The error message displayed on the buttons is too large to actually see

**Comment by chrislennon** [comment]
@Angel-Avila thanks for reporting the issue, sorry to hear you are having problems.

I just checked the API (https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC&tsyms=MEX) and it appears no price is being returned - I have reached out to CryptoCompare to ask if there is an issue on their end or if this is no longer a supported trading pair (in which case I will remove it from the tool)

I will keep this open and let you know any response I receive.

**Comment by chrislennon** [comment]
Well that's embarrassing - helps when I use the correct currency code... `MXN` not `MEX` as my code outputs 😅 

https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC&tsyms=MXN

corrected in 61d7a27 - fixed version live now!

**Comment by Angel-Avila** [comment]
Lmao it happens dude
I tried it now but there's just 2 issues:

1. The imported buttons' launch pad is set to `_usr_bin_python` for some reason
2. The python script when run, gives some invalid syntax errors, seems like a bunch of `/` where transformed to `_` for some reason

This *only* happens when importing directly to BTT, when you download the JSON and then import it, it doesn't

Btw: sorry for all the edits lol I came home with my brain fried and couldn't really see what was going on

**Comment by chrislennon** [comment]
No problem I wont be criticising after what I did 😂 

I believe the issue you describe has been fixed in a later BTT alpha version - see [here](https://github.com/chrislennon/Crypto-Touchbar-App/issues/88#issuecomment-418655263) for a similar discussion - close the issue if you get it working 😄

**Comment by Angel-Avila** [comment]
I thought it was somewhat related to the fix you did, but I see it wasn't. I updated to the latest alpha version and the issue is fixed (currently in v. 2.636).

Thanks man, I appreciate it!
