### ISSUE TITLE
“FIAT” is not an acronym unless you’re talking about cars

### ISSUE THREAD

**Issue by ticky** [chrislennon/Crypto-Touchbar-App#91]
cf.: [Fiat money on Wikipedia](https://en.wikipedia.org/wiki/Fiat_money), [Fiat Automobiles on Wikipedia](https://en.wikipedia.org/wiki/Fiat_Automobiles)

**Comment by chrislennon** [comment]
Hey @ticky thanks for raising this issue - you're completely correct I don't provide a conversion to a number of FIAT cars 😂 

Was originally a reference to fiat money and for unknown reasons was changed to FIAT. As this tool has changed over time, even using the term fiat money would probably be incorrect - some of the conversions aren't fiat monies and some of the coins are acting as fiat monies.

Will modify the non code references now, will pick up the references in the code with #90
