### ISSUE TITLE
add CRO to the list

### ISSUE THREAD

**Issue by fh-d** [chrislennon/Crypto-Touchbar-App#93]
Nice tool here,  you just convice me that the touch bar can be cool.
can you add the CRO coin ?

**Comment by chrislennon** [comment]
@fh-d thanks for the compliment! 

I believe if i'm looking at the correct coin it should already be supported. You will need to search the full name though `Crypto.com` (by token would be a nice feature - will flag that now)

Let me know if that works for you!

<img width="459" alt="Screenshot 2019-03-13 at 10 47 49" src="https://user-images.githubusercontent.com/9197696/54269335-7ce32400-457d-11e9-87fd-eee20fb9ace6.png">

**Comment by fh-d** [comment]
@chrislennon hey! thanks for this quick response.
En fait 
In fact i was thinking about the crypto.com chain token ( whis is CRO ). Crypto.com token ( previously MCO token ) is the one used for the ICO, CRO is for the project itself.

[Crypto.com](https://coinmarketcap.com/currencies/crypto-com/)  - MCO 
[Crypto.com Chain](https://coinmarketcap.com/currencies/crypto-com-chain/)  - CRO

unfortunately, it looks like it's doesn't listed on [CryptoCompare](https://www.cryptocompare.com/) :(

**Comment by chrislennon** [comment]
@fh-d yeah that seems to be exactly the problem, if its not on CryptoCompare I wont have access to any data.

Luckily no changes from me will be required - when its available on CryptoCompare it will instantly appear within the list 😄

**Comment by chrislennon** [comment]
looping back here seems like CRO was added to the API at some point in the last few months 🕺
