### ISSUE TITLE
Non of the icons are showing

### ISSUE THREAD

**Issue by alisalihoglu** [chrislennon/Crypto-Touchbar-App#94]
<img width="1085" alt="Touch Bar Shot 2019-06-22 at 12 38 38 AM" src="https://user-images.githubusercontent.com/52089320/59956109-217ed700-9486-11e9-8f62-f637c82056de.png">

**Comment by chrislennon** [comment]
Thanks for raising this @casuallyprivate - unfortunately I have been unable to replicate it.

Could you let me know the following so I can try to assist?
- Which version of BetterTouchTool
- Which browser used to generate
- Which mechanism for import you used (JSON or direct import)

I tested on BTT 3.085(1193) in Chrome with the direct import method.

**Comment by alisalihoglu** [comment]
Hi,
Thank you for the response.

- BTT version 3.085(1193)

- Brave Browser

- JSON

**Comment by chrislennon** [comment]
How strange, just tested in Brave with JSON and direct import and I still have icons. Trying to think of other ways to debug 🤔 

Are the icons appearing inside the BetterTouchTool, even if not showing on the touch bar?

Maybe could upload the exported JSON - may be able to identify what is wrong there, however may still not be able to determine what why it is being generated wrong 😟

**Comment by alisalihoglu** [comment]
Hi,
Sorry for the very very late reply :(...
I have downloaded another JSON file like 5 minutes ago. It still does not have the icons. I'm thinking maybe there is a problem with my settings.
Here is the file.
[Crypto-Touchbar-App-USD.json.zip](https://github.com/chrislennon/Crypto-Touchbar-App/files/3405683/Crypto-Touchbar-App-USD.json.zip)
Thank you!

**Comment by chrislennon** [comment]
@casuallyprivate - interesting! Can see from the JSON file that indeed the icon data isn't exported.

Not sure on how to proceed if I am honest seems tricky to replicate. 

In the mean time here is the same coins I believe you wished with the icon data embedded

[Crypto-Touchbar-App-USD.json.zip](https://github.com/chrislennon/Crypto-Touchbar-App/files/3413540/Crypto-Touchbar-App-USD.json.zip)

**Comment by alisalihoglu** [comment]
Maybe it is due to Brave browser, or the add-ons I'm using...
