### ISSUE TITLE
Display error: Traceback (most recent call last)

### ISSUE THREAD

**Issue by chtmorris** [chrislennon/Crypto-Touchbar-App#96]
I'm getting a display error. Each asset is displaying:
_Traceback (most recent call last):_

Love the tool. A fix would be great!

**Comment by chrislennon** [comment]
Hey @chtmorris thanks for the report. Could you open up BetterTouchTool, select one of the widgets and on the right hand side select `run script now` (red in screenshot) - if you can provide me with the whole error message (green in screenshot) I should be able to assist (The display is truncated on the assets itself)

<img width="1521" alt="Screenshot 2020-07-28 at 21 57 35" src="https://user-images.githubusercontent.com/9197696/88714880-b211f700-d11d-11ea-8f3e-1c09842c1fdd.png">

**Comment by chtmorris** [comment]
Hey @chrislennon! Thanks for getting back to me so quickly. The error says:

Traceback (most recent call last):
  File "<string>", line 25, in <module>
KeyError: 'RAW'

**Comment by chrislennon** [comment]
Very interesting @chtmorris - and slightly confusing 😅 

Looks like there is no data coming back from the API (it cant find any data in the `RAW` field). Might be quite hard to debug, however you could try going to [this link](https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC&tsyms=USD) (the default link we get data from) which may tell you more.

I have a hunch that the server is going to be giving something unexpected back - perhaps regarding rate limiting/maximum number of requests.

Given that this is probably going to be a touch of a tricky debug feel free to reach out to me on discord (or anything else more appropriate) leapyearboy#9316

**Comment by benzidirk** [comment]
Hi I get the same error everytime I enable my VPN. Is there a workaround?

**Comment by RexYuan** [comment]
Hey there I get the API lock too. Cryptocompare gives

```
{"Response":"Error","Message":"You are over your rate limit please upgrade your account!","HasWarning":false,"Type":99,"RateLimit":{"calls_made":{"second":1,"minute":2,"hour":415,"day":7625,"month":13633,"total_calls":13633},"max_calls":{"second":20,"minute":300,"hour":3000,"day":7500,"month":50000}},"Data":{}}
```

**Comment by chrislennon** [comment]
Apologies for missing notifications on this.

@benzidirk - there is likely other users on your VPN (assuming its public/semi-private) using Cryptocompare's API which will be adding to your quota (by IP).

@RexYuan - As the error says you are also hitting the quota that CryptoCompare has set up.

To both of you - there is some potential workarounds you may wish to try over on [this comment](https://github.com/chrislennon/Crypto-Touchbar-App/issues/95#issuecomment-616113850) and [this comment](https://github.com/chrislennon/Crypto-Touchbar-App/issues/100#issuecomment-803287084) however it likely depend much on your usage (if you are still using this that is 😅)

Moving this issue to closed but if you continue to have issues please open another issue, will be happy to debug with you.
